var namespacefastly_1_1detail_1_1rust__bridge__tags_1_1esi =
[
    [ "DispatchFragmentRequestFnTag", "structfastly_1_1detail_1_1rust__bridge__tags_1_1esi_1_1DispatchFragmentRequestFnTag.html", "structfastly_1_1detail_1_1rust__bridge__tags_1_1esi_1_1DispatchFragmentRequestFnTag" ],
    [ "ProcessFragmentResponseFnTag", "structfastly_1_1detail_1_1rust__bridge__tags_1_1esi_1_1ProcessFragmentResponseFnTag.html", "structfastly_1_1detail_1_1rust__bridge__tags_1_1esi_1_1ProcessFragmentResponseFnTag" ]
];